# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: election.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'election.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65lection.proto\x12\x08\x65lection\"Y\n\x0c\x45lectionData\x12\x10\n\x08regionID\x18\x01 \x01(\t\x12\x16\n\x0e\x65lectionRegion\x18\x02 \x01(\t\x12\x1f\n\x06partys\x18\x04 \x03(\x0b\x32\x0f.election.Party\"d\n\x05Party\x12\x0f\n\x07partyID\x18\x01 \x01(\x05\x12\x11\n\tpartyName\x18\x02 \x01(\t\x12(\n\x06vorzug\x18\x03 \x03(\x0b\x32\x18.election.Vorzugsstimmen\x12\r\n\x05votes\x18\x04 \x01(\x05\"Q\n\x0eVorzugsstimmen\x12\x12\n\nvorzugName\x18\x01 \x01(\t\x12\x15\n\rstimmenAnzahl\x18\x02 \x01(\x05\x12\x14\n\x0clistennummer\x18\x03 \x01(\x05\"\"\n\x0eMessageRequest\x12\x10\n\x08regionID\x18\x01 \x01(\t\"\'\n\x0fMessageResponse\x12\x14\n\x0cresponseData\x18\x01 \x01(\t2Z\n\x0f\x45lectionService\x12G\n\x12GetElectionResults\x12\x16.election.ElectionData\x1a\x19.election.MessageResponseB\x12\n\x10io.grpc.electionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'election_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020io.grpc.election'
  _globals['_ELECTIONDATA']._serialized_start=28
  _globals['_ELECTIONDATA']._serialized_end=117
  _globals['_PARTY']._serialized_start=119
  _globals['_PARTY']._serialized_end=219
  _globals['_VORZUGSSTIMMEN']._serialized_start=221
  _globals['_VORZUGSSTIMMEN']._serialized_end=302
  _globals['_MESSAGEREQUEST']._serialized_start=304
  _globals['_MESSAGEREQUEST']._serialized_end=338
  _globals['_MESSAGERESPONSE']._serialized_start=340
  _globals['_MESSAGERESPONSE']._serialized_end=379
  _globals['_ELECTIONSERVICE']._serialized_start=381
  _globals['_ELECTIONSERVICE']._serialized_end=471
# @@protoc_insertion_point(module_scope)
